// BU DOSYA SQLITE VERİTABANINDAN OTOMATİK OLUŞTURULMUŞTUR
export const leagues = [
  { id: 'superlig', name: 'Türkiye Elit Ligi', country: 'Türkiye' }
];

export const clubs = [
  {
    "id": "645",
    "name": "İstanbul Aslanları",
    "shortName": "İST",
    "leagueId": "superlig",
    "city": "İstanbul",
    "stadium": "RAMS Park",
    "capacity": 53798,
    "prestige": 8,
    "budget": 50,
    "founded": 1905,
    "logo": null,
    "colors": {
      "primary": "#000000",
      "secondary": "#ffffff"
    }
  },
  {
    "id": "611",
    "name": "Kadıköy Kanaryaları",
    "shortName": "KAD",
    "leagueId": "superlig",
    "city": "İstanbul",
    "stadium": "Chobani Stadyumu Fenerbahçe Şükrü Saracoğlu Spor Kompleksi",
    "capacity": 47834,
    "prestige": 8,
    "budget": 50,
    "founded": 1907,
    "logo": null,
    "colors": {
      "primary": "#000000",
      "secondary": "#ffffff"
    }
  },
  {
    "id": "549",
    "name": "Boğaziçi Kartalları",
    "shortName": "BOĞ",
    "leagueId": "superlig",
    "city": "İstanbul",
    "stadium": "Tüpraş Stadyumu",
    "capacity": 43500,
    "prestige": 8,
    "budget": 50,
    "founded": 1903,
    "logo": null,
    "colors": {
      "primary": "#000000",
      "secondary": "#ffffff"
    }
  },
  {
    "id": "998",
    "name": "Karadeniz Fırtınası",
    "shortName": "KAR",
    "leagueId": "superlig",
    "city": "Trabzon",
    "stadium": "Papara Park",
    "capacity": 41513,
    "prestige": 8,
    "budget": 50,
    "founded": 1967,
    "logo": null,
    "colors": {
      "primary": "#000000",
      "secondary": "#ffffff"
    }
  }
];

export const players = [
  {
    "id": "cmrnsmov10001kp2p989tt22h",
    "apiId": 49866,
    "firstName": "U.",
    "lastName": "Çakar",
    "age": 29,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "GK",
    "overall": 78,
    "pac": 81,
    "sho": 68,
    "pas": 74,
    "dri": 78,
    "def": 63,
    "phy": 74,
    "value": 8,
    "wage": 45,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 78,
    "photo": null
  },
  {
    "id": "cmrnsmov50003kp2psf2hgbvt",
    "apiId": 61950,
    "firstName": "G.",
    "lastName": "Güvanç",
    "age": 34,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "GK",
    "overall": 72,
    "pac": 72,
    "sho": 62,
    "pas": 73,
    "dri": 74,
    "def": 57,
    "phy": 68,
    "value": 5,
    "wage": 52,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 73,
    "photo": null
  },
  {
    "id": "cmrnsmov70005kp2peyr4hqb5",
    "apiId": 568439,
    "firstName": "A.",
    "lastName": "Yilmoz",
    "age": 17,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "GK",
    "overall": 73,
    "pac": 76,
    "sho": 63,
    "pas": 74,
    "dri": 71,
    "def": 58,
    "phy": 68,
    "value": 9,
    "wage": 29,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 76,
    "photo": null
  },
  {
    "id": "cmrnsmov90007kp2ph6p6k67l",
    "apiId": 25448,
    "firstName": "K.",
    "lastName": "Ayhon",
    "age": 31,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "CB",
    "overall": 77,
    "pac": 81,
    "sho": 67,
    "pas": 74,
    "dri": 73,
    "def": 92,
    "phy": 81,
    "value": 10,
    "wage": 44,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 77,
    "photo": null
  },
  {
    "id": "cmrnsmovb0009kp2p8j8skabo",
    "apiId": 61837,
    "firstName": "A.",
    "lastName": "Bardakca",
    "age": 31,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "CB",
    "overall": 79,
    "pac": 81,
    "sho": 69,
    "pas": 77,
    "dri": 76,
    "def": 94,
    "phy": 80,
    "value": 15,
    "wage": 23,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 80,
    "photo": null
  },
  {
    "id": "cmrnsmove000bkp2pare9ma4w",
    "apiId": 50057,
    "firstName": "E.",
    "lastName": "Elmala",
    "age": 25,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "CB",
    "overall": 81,
    "pac": 77,
    "sho": 71,
    "pas": 76,
    "dri": 85,
    "def": 96,
    "phy": 84,
    "value": 14,
    "wage": 57,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 83,
    "photo": null
  },
  {
    "id": "cmrnsmovg000dkp2p153e5np1",
    "apiId": 158121,
    "firstName": "I.",
    "lastName": "Jakubs",
    "age": 26,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "CB",
    "overall": 71,
    "pac": 67,
    "sho": 61,
    "pas": 73,
    "dri": 74,
    "def": 86,
    "phy": 67,
    "value": 3,
    "wage": 31,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 75,
    "photo": null
  },
  {
    "id": "cmrnsmovj000fkp2ps4aae6hn",
    "apiId": 568393,
    "firstName": "Y.",
    "lastName": "Kahramon",
    "age": 17,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "CB",
    "overall": 80,
    "pac": 81,
    "sho": 70,
    "pas": 81,
    "dri": 81,
    "def": 95,
    "phy": 79,
    "value": 1,
    "wage": 42,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 81,
    "photo": null
  },
  {
    "id": "cmrnsmovm000hkp2p41qv8mpr",
    "apiId": 145057,
    "firstName": "K.",
    "lastName": "Karatoş",
    "age": 23,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "CB",
    "overall": 78,
    "pac": 73,
    "sho": 68,
    "pas": 73,
    "dri": 75,
    "def": 93,
    "phy": 75,
    "value": 1,
    "wage": 12,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 79,
    "photo": null
  },
  {
    "id": "cmrnsmovp000jkp2polos6auo",
    "apiId": 26252,
    "firstName": "R.",
    "lastName": "Sallae",
    "age": 28,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "CB",
    "overall": 79,
    "pac": 79,
    "sho": 69,
    "pas": 76,
    "dri": 79,
    "def": 94,
    "phy": 83,
    "value": 14,
    "wage": 21,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 79,
    "photo": null
  },
  {
    "id": "cmrnsmovs000lkp2pir0uq6ig",
    "apiId": 168,
    "firstName": "D.",
    "lastName": "Sánchaz",
    "age": 29,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "CB",
    "overall": 72,
    "pac": 67,
    "sho": 62,
    "pas": 73,
    "dri": 72,
    "def": 87,
    "phy": 72,
    "value": 7,
    "wage": 45,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 76,
    "photo": null
  },
  {
    "id": "cmrnsmovu000nkp2p9gc0wi5u",
    "apiId": 30504,
    "firstName": "W.",
    "lastName": "Singu",
    "age": 25,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "CB",
    "overall": 82,
    "pac": 85,
    "sho": 72,
    "pas": 86,
    "dri": 82,
    "def": 97,
    "phy": 83,
    "value": 11,
    "wage": 47,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 86,
    "photo": null
  },
  {
    "id": "cmrnsmovx000pkp2prs46olz1",
    "apiId": 404443,
    "firstName": "A.",
    "lastName": "Ünyoy",
    "age": 19,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "CB",
    "overall": 72,
    "pac": 76,
    "sho": 62,
    "pas": 76,
    "dri": 76,
    "def": 87,
    "phy": 74,
    "value": 12,
    "wage": 18,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 73,
    "photo": null
  },
  {
    "id": "cmrnsmow1000rkp2pz31vn7dt",
    "apiId": 567984,
    "firstName": "C.",
    "lastName": "Akgan",
    "age": 16,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "CM",
    "overall": 76,
    "pac": 75,
    "sho": 66,
    "pas": 72,
    "dri": 72,
    "def": 61,
    "phy": 78,
    "value": 14,
    "wage": 30,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 78,
    "photo": null
  },
  {
    "id": "cmrnsmow3000tkp2pch830oid",
    "apiId": 80552,
    "firstName": "G.",
    "lastName": "Saro",
    "age": 26,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "CM",
    "overall": 79,
    "pac": 75,
    "sho": 69,
    "pas": 76,
    "dri": 78,
    "def": 64,
    "phy": 80,
    "value": 6,
    "wage": 50,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 82,
    "photo": null
  },
  {
    "id": "cmrnsmow6000vkp2pxssyp1hf",
    "apiId": 633,
    "firstName": "İ.",
    "lastName": "Gündoğon",
    "age": 35,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "CM",
    "overall": 73,
    "pac": 73,
    "sho": 63,
    "pas": 73,
    "dri": 74,
    "def": 58,
    "phy": 77,
    "value": 2,
    "wage": 25,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 75,
    "photo": null
  },
  {
    "id": "cmrnsmow8000xkp2pre2lsaaq",
    "apiId": 518567,
    "firstName": "R.",
    "lastName": "Nhago",
    "age": 18,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "CM",
    "overall": 71,
    "pac": 73,
    "sho": 61,
    "pas": 72,
    "dri": 66,
    "def": 56,
    "phy": 67,
    "value": 5,
    "wage": 34,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 71,
    "photo": null
  },
  {
    "id": "cmrnsmowi000zkp2p2d0w19v3",
    "apiId": 567979,
    "firstName": "N.",
    "lastName": "Ogulcan Yancal",
    "age": 16,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "CM",
    "overall": 74,
    "pac": 77,
    "sho": 64,
    "pas": 70,
    "dri": 76,
    "def": 59,
    "phy": 71,
    "value": 6,
    "wage": 24,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 77,
    "photo": null
  },
  {
    "id": "cmrnsmows0011kp2pcb32l064",
    "apiId": 1462,
    "firstName": "L.",
    "lastName": "Torreiro",
    "age": 29,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "CM",
    "overall": 83,
    "pac": 84,
    "sho": 73,
    "pas": 80,
    "dri": 82,
    "def": 68,
    "phy": 78,
    "value": 6,
    "wage": 15,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 85,
    "photo": null
  },
  {
    "id": "cmrnsmoww0013kp2pyb388q3d",
    "apiId": 454,
    "firstName": "Y.",
    "lastName": "Akgun",
    "age": 25,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "ST",
    "overall": 78,
    "pac": 75,
    "sho": 88,
    "pas": 77,
    "dri": 82,
    "def": 63,
    "phy": 74,
    "value": 5,
    "wage": 57,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 78,
    "photo": null
  },
  {
    "id": "cmrnsmox40015kp2p7scdudzm",
    "apiId": 585709,
    "firstName": "C.",
    "lastName": "Gunar",
    "age": 17,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "ST",
    "overall": 72,
    "pac": 71,
    "sho": 82,
    "pas": 74,
    "dri": 70,
    "def": 57,
    "phy": 69,
    "value": 13,
    "wage": 10,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 73,
    "photo": null
  },
  {
    "id": "cmrnsmox60017kp2puw60gt6g",
    "apiId": 498673,
    "firstName": "F.",
    "lastName": "Koçok",
    "age": 17,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "ST",
    "overall": 75,
    "pac": 76,
    "sho": 85,
    "pas": 77,
    "dri": 73,
    "def": 60,
    "phy": 70,
    "value": 7,
    "wage": 27,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 78,
    "photo": null
  },
  {
    "id": "cmrnsmox90019kp2pknnw7ukh",
    "apiId": 422,
    "firstName": "A.",
    "lastName": "Kutuca",
    "age": 25,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "ST",
    "overall": 70,
    "pac": 66,
    "sho": 80,
    "pas": 67,
    "dri": 65,
    "def": 55,
    "phy": 66,
    "value": 9,
    "wage": 31,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 74,
    "photo": null
  },
  {
    "id": "cmrnsmoxc001bkp2pj8fk46gz",
    "apiId": 2780,
    "firstName": "V.",
    "lastName": "Osimhan",
    "age": 27,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "ST",
    "overall": 72,
    "pac": 73,
    "sho": 82,
    "pas": 67,
    "dri": 69,
    "def": 57,
    "phy": 71,
    "value": 13,
    "wage": 41,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 76,
    "photo": null
  },
  {
    "id": "cmrnsmoxe001dkp2prs3s6cnx",
    "apiId": 644,
    "firstName": "L.",
    "lastName": "Soné",
    "age": 30,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "ST",
    "overall": 82,
    "pac": 79,
    "sho": 92,
    "pas": 84,
    "dri": 78,
    "def": 67,
    "phy": 81,
    "value": 5,
    "wage": 57,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 86,
    "photo": null
  },
  {
    "id": "cmrnsmoxg001fkp2pxc0h11ll",
    "apiId": 63274,
    "firstName": "B.",
    "lastName": "Yılmoz",
    "age": 25,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "ST",
    "overall": 77,
    "pac": 75,
    "sho": 87,
    "pas": 79,
    "dri": 73,
    "def": 62,
    "phy": 79,
    "value": 13,
    "wage": 11,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 77,
    "photo": null
  },
  {
    "id": "cmrnsmoxi001hkp2pt179fzqi",
    "apiId": 602698,
    "firstName": "A.",
    "lastName": "Yuzgac",
    "age": 16,
    "nationality": "Bilinmiyor",
    "clubId": "645",
    "position": "ST",
    "overall": 83,
    "pac": 79,
    "sho": 93,
    "pas": 86,
    "dri": 86,
    "def": 68,
    "phy": 80,
    "value": 1,
    "wage": 16,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 83,
    "photo": null
  },
  {
    "id": "cmrnsmqws001jkp2pm3h3cw2p",
    "apiId": 500088,
    "firstName": "E.",
    "lastName": "Biterga",
    "age": 19,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "GK",
    "overall": 77,
    "pac": 72,
    "sho": 67,
    "pas": 72,
    "dri": 80,
    "def": 62,
    "phy": 76,
    "value": 8,
    "wage": 18,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 77,
    "photo": null
  },
  {
    "id": "cmrnsmqww001lkp2pgz6q96aq",
    "apiId": 62401,
    "firstName": "T.",
    "lastName": "Çeten",
    "age": 29,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "GK",
    "overall": 75,
    "pac": 79,
    "sho": 65,
    "pas": 76,
    "dri": 74,
    "def": 60,
    "phy": 77,
    "value": 9,
    "wage": 44,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 76,
    "photo": null
  },
  {
    "id": "cmrnsmqwz001nkp2pvlpor8r4",
    "apiId": 643580,
    "firstName": "H.",
    "lastName": "Efe Ceylon",
    "age": 17,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "GK",
    "overall": 71,
    "pac": 73,
    "sho": 61,
    "pas": 68,
    "dri": 66,
    "def": 56,
    "phy": 74,
    "value": 1,
    "wage": 33,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 73,
    "photo": null
  },
  {
    "id": "cmrnsmqx2001pkp2p21iyy9cn",
    "apiId": 617,
    "firstName": "E.",
    "lastName": "Edersun",
    "age": 32,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "GK",
    "overall": 73,
    "pac": 74,
    "sho": 63,
    "pas": 71,
    "dri": 77,
    "def": 58,
    "phy": 76,
    "value": 13,
    "wage": 11,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 75,
    "photo": null
  },
  {
    "id": "cmrnsmqx5001rkp2pgh7yhptt",
    "apiId": 62137,
    "firstName": "İ.",
    "lastName": "Eğribayot",
    "age": 27,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "GK",
    "overall": 79,
    "pac": 79,
    "sho": 69,
    "pas": 79,
    "dri": 83,
    "def": 64,
    "phy": 80,
    "value": 9,
    "wage": 16,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 79,
    "photo": null
  },
  {
    "id": "cmrnsmqx7001tkp2p3h00hxwc",
    "apiId": 49837,
    "firstName": "M.",
    "lastName": "Günuk",
    "age": 36,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "GK",
    "overall": 77,
    "pac": 80,
    "sho": 67,
    "pas": 74,
    "dri": 78,
    "def": 62,
    "phy": 74,
    "value": 13,
    "wage": 44,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 78,
    "photo": null
  },
  {
    "id": "cmrnsmqxa001vkp2pjfcdt1mb",
    "apiId": 18861,
    "firstName": "N.",
    "lastName": "Oké",
    "age": 30,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CB",
    "overall": 71,
    "pac": 74,
    "sho": 61,
    "pas": 71,
    "dri": 71,
    "def": 86,
    "phy": 70,
    "value": 10,
    "wage": 33,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 75,
    "photo": null
  },
  {
    "id": "cmrnsmqxc001xkp2p8ztb3krm",
    "apiId": 161661,
    "firstName": "A.",
    "lastName": "Bruwn",
    "age": 23,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CB",
    "overall": 74,
    "pac": 72,
    "sho": 64,
    "pas": 75,
    "dri": 69,
    "def": 89,
    "phy": 70,
    "value": 9,
    "wage": 14,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 74,
    "photo": null
  },
  {
    "id": "cmrnsmqxe001zkp2pc4dc6ksk",
    "apiId": 364594,
    "firstName": "Y.",
    "lastName": "Demer",
    "age": 21,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CB",
    "overall": 73,
    "pac": 76,
    "sho": 63,
    "pas": 76,
    "dri": 71,
    "def": 88,
    "phy": 68,
    "value": 1,
    "wage": 34,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 77,
    "photo": null
  },
  {
    "id": "cmrnsmqxh0021kp2p3lnhvj1r",
    "apiId": 436386,
    "firstName": "Y.",
    "lastName": "Fidon",
    "age": 20,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CB",
    "overall": 77,
    "pac": 81,
    "sho": 67,
    "pas": 81,
    "dri": 76,
    "def": 92,
    "phy": 77,
    "value": 2,
    "wage": 41,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 79,
    "photo": null
  },
  {
    "id": "cmrnsmqxj0023kp2pvqqjn9mg",
    "apiId": 127609,
    "firstName": "L.",
    "lastName": "Mercon",
    "age": 25,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CB",
    "overall": 84,
    "pac": 81,
    "sho": 74,
    "pas": 85,
    "dri": 80,
    "def": 99,
    "phy": 82,
    "value": 3,
    "wage": 11,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 85,
    "photo": null
  },
  {
    "id": "cmrnsmqxl0025kp2p8c940wo4",
    "apiId": 340727,
    "firstName": "O.",
    "lastName": "MimoveÄ",
    "age": 21,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CB",
    "overall": 76,
    "pac": 74,
    "sho": 66,
    "pas": 75,
    "dri": 76,
    "def": 91,
    "phy": 73,
    "value": 15,
    "wage": 39,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 77,
    "photo": null
  },
  {
    "id": "cmrnsmqxn0027kp2p9ge1xf0o",
    "apiId": 1719,
    "firstName": "M.",
    "lastName": "Müldur",
    "age": 26,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CB",
    "overall": 75,
    "pac": 78,
    "sho": 65,
    "pas": 79,
    "dri": 76,
    "def": 90,
    "phy": 70,
    "value": 11,
    "wage": 41,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 77,
    "photo": null
  },
  {
    "id": "cmrnsmqxq0029kp2p7yq0e0s7",
    "apiId": 272721,
    "firstName": "J.",
    "lastName": "Oosterwolda",
    "age": 24,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CB",
    "overall": 77,
    "pac": 72,
    "sho": 67,
    "pas": 80,
    "dri": 78,
    "def": 92,
    "phy": 76,
    "value": 11,
    "wage": 43,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 81,
    "photo": null
  },
  {
    "id": "cmrnsmqxs002bkp2p88wqwa1u",
    "apiId": 829,
    "firstName": "R.",
    "lastName": "Becãu",
    "age": 30,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CB",
    "overall": 71,
    "pac": 74,
    "sho": 61,
    "pas": 69,
    "dri": 70,
    "def": 86,
    "phy": 66,
    "value": 8,
    "wage": 12,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 73,
    "photo": null
  },
  {
    "id": "cmrnsmqxu002dkp2ppjyzfbt4",
    "apiId": 130,
    "firstName": "N.",
    "lastName": "Semedu",
    "age": 32,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CB",
    "overall": 70,
    "pac": 69,
    "sho": 60,
    "pas": 73,
    "dri": 72,
    "def": 85,
    "phy": 70,
    "value": 11,
    "wage": 47,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 70,
    "photo": null
  },
  {
    "id": "cmrnsmqxw002fkp2pf8xfih8j",
    "apiId": 616727,
    "firstName": "Y.",
    "lastName": "San",
    "age": 17,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CB",
    "overall": 83,
    "pac": 79,
    "sho": 73,
    "pas": 80,
    "dri": 86,
    "def": 98,
    "phy": 79,
    "value": 5,
    "wage": 55,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 84,
    "photo": null
  },
  {
    "id": "cmrnsmqxz002hkp2pyl3m3d08",
    "apiId": 198,
    "firstName": "M.",
    "lastName": "Škrinior",
    "age": 30,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CB",
    "overall": 79,
    "pac": 77,
    "sho": 69,
    "pas": 78,
    "dri": 80,
    "def": 94,
    "phy": 81,
    "value": 7,
    "wage": 13,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 79,
    "photo": null
  },
  {
    "id": "cmrnsmqy1002jkp2p31wmwst1",
    "apiId": 18776,
    "firstName": "Ç.",
    "lastName": "Söyüncu",
    "age": 29,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CB",
    "overall": 72,
    "pac": 68,
    "sho": 62,
    "pas": 74,
    "dri": 67,
    "def": 87,
    "phy": 76,
    "value": 5,
    "wage": 54,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 73,
    "photo": null
  },
  {
    "id": "cmrnsmqy3002lkp2py2fr3ykg",
    "apiId": 625426,
    "firstName": "K.",
    "lastName": "Efe Üregan",
    "age": 17,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CB",
    "overall": 70,
    "pac": 72,
    "sho": 60,
    "pas": 73,
    "dri": 72,
    "def": 85,
    "phy": 66,
    "value": 10,
    "wage": 34,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 72,
    "photo": null
  },
  {
    "id": "cmrnsmqy5002nkp2pr0h2343m",
    "apiId": 134590,
    "firstName": "O.",
    "lastName": "Aydan",
    "age": 25,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CM",
    "overall": 83,
    "pac": 84,
    "sho": 73,
    "pas": 86,
    "dri": 83,
    "def": 68,
    "phy": 79,
    "value": 15,
    "wage": 53,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 87,
    "photo": null
  },
  {
    "id": "cmrnsmqy8002pkp2pda6ok3lm",
    "apiId": 50129,
    "firstName": "E.",
    "lastName": "Demer",
    "age": 22,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CM",
    "overall": 83,
    "pac": 87,
    "sho": 73,
    "pas": 86,
    "dri": 84,
    "def": 68,
    "phy": 86,
    "value": 12,
    "wage": 57,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 87,
    "photo": null
  },
  {
    "id": "cmrnsmqyb002rkp2pl21c2s10",
    "apiId": 630584,
    "firstName": "A.",
    "lastName": "Ekice",
    "age": 17,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CM",
    "overall": 76,
    "pac": 73,
    "sho": 66,
    "pas": 79,
    "dri": 79,
    "def": 61,
    "phy": 79,
    "value": 12,
    "wage": 48,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 80,
    "photo": null
  },
  {
    "id": "cmrnsmqyd002tkp2p40yxt9e6",
    "apiId": 162004,
    "firstName": "B.",
    "lastName": "Elmoz",
    "age": 22,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CM",
    "overall": 71,
    "pac": 67,
    "sho": 61,
    "pas": 71,
    "dri": 73,
    "def": 56,
    "phy": 69,
    "value": 10,
    "wage": 37,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 73,
    "photo": null
  },
  {
    "id": "cmrnsmqyf002vkp2pawe3ruf5",
    "apiId": 647548,
    "firstName": "A.",
    "lastName": "E. Fettahogla",
    "age": 17,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CM",
    "overall": 83,
    "pac": 84,
    "sho": 73,
    "pas": 84,
    "dri": 87,
    "def": 68,
    "phy": 87,
    "value": 13,
    "wage": 43,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 85,
    "photo": null
  },
  {
    "id": "cmrnsmqyi002xkp2pkcduahz7",
    "apiId": 905,
    "firstName": "F.",
    "lastName": "Frad",
    "age": 32,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CM",
    "overall": 72,
    "pac": 72,
    "sho": 62,
    "pas": 68,
    "dri": 68,
    "def": 57,
    "phy": 70,
    "value": 11,
    "wage": 19,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 73,
    "photo": null
  },
  {
    "id": "cmrnsmqyl002zkp2pst01hjj7",
    "apiId": 1454,
    "firstName": "M.",
    "lastName": "Guendouze",
    "age": 26,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CM",
    "overall": 83,
    "pac": 82,
    "sho": 73,
    "pas": 79,
    "dri": 86,
    "def": 68,
    "phy": 84,
    "value": 7,
    "wage": 56,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 85,
    "photo": null
  },
  {
    "id": "cmrnsmqyn0031kp2pri8e8wav",
    "apiId": 2290,
    "firstName": "N.",
    "lastName": "Konté",
    "age": 34,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CM",
    "overall": 76,
    "pac": 78,
    "sho": 66,
    "pas": 74,
    "dri": 72,
    "def": 61,
    "phy": 71,
    "value": 8,
    "wage": 36,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 77,
    "photo": null
  },
  {
    "id": "cmrnsmqyp0033kp2pw2tr7xnc",
    "apiId": 302869,
    "firstName": "N.",
    "lastName": "Dorgelas",
    "age": 23,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CM",
    "overall": 76,
    "pac": 72,
    "sho": 66,
    "pas": 75,
    "dri": 72,
    "def": 61,
    "phy": 76,
    "value": 4,
    "wage": 49,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 78,
    "photo": null
  },
  {
    "id": "cmrnsmqyr0035kp2p1sooe8yo",
    "apiId": 12724,
    "firstName": "T.",
    "lastName": "Talisco",
    "age": 32,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CM",
    "overall": 83,
    "pac": 78,
    "sho": 73,
    "pas": 81,
    "dri": 83,
    "def": 68,
    "phy": 84,
    "value": 11,
    "wage": 50,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 84,
    "photo": null
  },
  {
    "id": "cmrnsmqyu0037kp2phg1bxtxg",
    "apiId": 214463,
    "firstName": "İ.",
    "lastName": "Yüksak",
    "age": 27,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "CM",
    "overall": 77,
    "pac": 81,
    "sho": 67,
    "pas": 74,
    "dri": 77,
    "def": 62,
    "phy": 73,
    "value": 5,
    "wage": 56,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 80,
    "photo": null
  },
  {
    "id": "cmrnsmqyw0039kp2pxz57az91",
    "apiId": 142959,
    "firstName": "K.",
    "lastName": "Aktürkoğla",
    "age": 27,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "ST",
    "overall": 75,
    "pac": 73,
    "sho": 85,
    "pas": 70,
    "dri": 73,
    "def": 60,
    "phy": 78,
    "value": 1,
    "wage": 28,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 77,
    "photo": null
  },
  {
    "id": "cmrnsmqyz003bkp2p2kpcq4oq",
    "apiId": 746,
    "firstName": "M.",
    "lastName": "Asensiu",
    "age": 30,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "ST",
    "overall": 74,
    "pac": 78,
    "sho": 84,
    "pas": 75,
    "dri": 77,
    "def": 59,
    "phy": 75,
    "value": 11,
    "wage": 40,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 76,
    "photo": null
  },
  {
    "id": "cmrnsmqz2003dkp2pda70kvdn",
    "apiId": 421875,
    "firstName": "S.",
    "lastName": "Cheref",
    "age": 19,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "ST",
    "overall": 84,
    "pac": 84,
    "sho": 94,
    "pas": 79,
    "dri": 85,
    "def": 69,
    "phy": 81,
    "value": 3,
    "wage": 21,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 85,
    "photo": null
  },
  {
    "id": "cmrnsmqz4003fkp2pcr0f3sym",
    "apiId": 417861,
    "firstName": "A.",
    "lastName": "Dioaf",
    "age": 17,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "ST",
    "overall": 71,
    "pac": 72,
    "sho": 81,
    "pas": 69,
    "dri": 69,
    "def": 56,
    "phy": 70,
    "value": 14,
    "wage": 33,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 74,
    "photo": null
  },
  {
    "id": "cmrnsmqz7003hkp2piw88mkgw",
    "apiId": 601310,
    "firstName": "C.",
    "lastName": "Fedae",
    "age": 19,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "ST",
    "overall": 82,
    "pac": 84,
    "sho": 92,
    "pas": 85,
    "dri": 84,
    "def": 67,
    "phy": 82,
    "value": 14,
    "wage": 10,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 85,
    "photo": null
  },
  {
    "id": "cmrnsmqza003jkp2pc3dojwgo",
    "apiId": 49857,
    "firstName": "İ.",
    "lastName": "Kahvece",
    "age": 30,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "ST",
    "overall": 78,
    "pac": 81,
    "sho": 88,
    "pas": 74,
    "dri": 76,
    "def": 63,
    "phy": 82,
    "value": 12,
    "wage": 35,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 82,
    "photo": null
  },
  {
    "id": "cmrnsmqzc003lkp2ps0m6hani",
    "apiId": 50048,
    "firstName": "V.",
    "lastName": "Muriqe",
    "age": 31,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "ST",
    "overall": 74,
    "pac": 78,
    "sho": 84,
    "pas": 71,
    "dri": 76,
    "def": 59,
    "phy": 77,
    "value": 8,
    "wage": 36,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 75,
    "photo": null
  },
  {
    "id": "cmrnsmqzf003nkp2psqj8ae3j",
    "apiId": 37380,
    "firstName": "A.",
    "lastName": "Musabo",
    "age": 25,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "ST",
    "overall": 72,
    "pac": 68,
    "sho": 82,
    "pas": 67,
    "dri": 73,
    "def": 57,
    "phy": 73,
    "value": 12,
    "wage": 51,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 76,
    "photo": null
  },
  {
    "id": "cmrnsmqzh003pkp2psps3m6jx",
    "apiId": 634143,
    "firstName": "E.",
    "lastName": "Sancakle",
    "age": 17,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "ST",
    "overall": 82,
    "pac": 77,
    "sho": 92,
    "pas": 83,
    "dri": 82,
    "def": 67,
    "phy": 84,
    "value": 6,
    "wage": 53,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 86,
    "photo": null
  },
  {
    "id": "cmrnsmqzk003rkp2p518n6t8b",
    "apiId": 602697,
    "firstName": "E.",
    "lastName": "Sayor",
    "age": 17,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "ST",
    "overall": 79,
    "pac": 80,
    "sho": 89,
    "pas": 83,
    "dri": 82,
    "def": 64,
    "phy": 74,
    "value": 6,
    "wage": 24,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 80,
    "photo": null
  },
  {
    "id": "cmrnsmqzm003tkp2p0c4vipmc",
    "apiId": 785,
    "firstName": "C.",
    "lastName": "Ündar",
    "age": 28,
    "nationality": "Bilinmiyor",
    "clubId": "611",
    "position": "ST",
    "overall": 83,
    "pac": 79,
    "sho": 93,
    "pas": 78,
    "dri": 84,
    "def": 68,
    "phy": 80,
    "value": 11,
    "wage": 25,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 84,
    "photo": null
  },
  {
    "id": "cmrnsmson003vkp2p4ieqpkd5",
    "apiId": 50104,
    "firstName": "D.",
    "lastName": "Alemdor",
    "age": 23,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "GK",
    "overall": 79,
    "pac": 79,
    "sho": 69,
    "pas": 76,
    "dri": 78,
    "def": 64,
    "phy": 80,
    "value": 13,
    "wage": 42,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 79,
    "photo": null
  },
  {
    "id": "cmrnsmsoq003xkp2pm905qpf1",
    "apiId": 275090,
    "firstName": "E.",
    "lastName": "Bilgen",
    "age": 21,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "GK",
    "overall": 71,
    "pac": 70,
    "sho": 61,
    "pas": 74,
    "dri": 75,
    "def": 56,
    "phy": 73,
    "value": 1,
    "wage": 26,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 74,
    "photo": null
  },
  {
    "id": "cmrnsmsos003zkp2p1ui7aiwh",
    "apiId": 399,
    "firstName": "A.",
    "lastName": "Nübal",
    "age": 29,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "GK",
    "overall": 84,
    "pac": 84,
    "sho": 74,
    "pas": 88,
    "dri": 82,
    "def": 69,
    "phy": 79,
    "value": 2,
    "wage": 24,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 85,
    "photo": null
  },
  {
    "id": "cmrnsmsov0041kp2pmj4ewuwu",
    "apiId": 544926,
    "firstName": "E.",
    "lastName": "Yasor",
    "age": 20,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "GK",
    "overall": 70,
    "pac": 74,
    "sho": 60,
    "pas": 73,
    "dri": 74,
    "def": 55,
    "phy": 73,
    "value": 15,
    "wage": 39,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 73,
    "photo": null
  },
  {
    "id": "cmrnsmsox0043kp2phn91eaf7",
    "apiId": 135068,
    "firstName": "E.",
    "lastName": "Agbadoa",
    "age": 28,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CB",
    "overall": 71,
    "pac": 70,
    "sho": 61,
    "pas": 69,
    "dri": 70,
    "def": 86,
    "phy": 75,
    "value": 12,
    "wage": 48,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 72,
    "photo": null
  },
  {
    "id": "cmrnsmsp00045kp2p9bke6q2v",
    "apiId": 394663,
    "firstName": "T.",
    "lastName": " Bulat",
    "age": 20,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CB",
    "overall": 73,
    "pac": 70,
    "sho": 63,
    "pas": 76,
    "dri": 70,
    "def": 88,
    "phy": 75,
    "value": 4,
    "wage": 15,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 75,
    "photo": null
  },
  {
    "id": "cmrnsmsp20047kp2p6kjtr88v",
    "apiId": 1479,
    "firstName": "T.",
    "lastName": "Djoló",
    "age": 25,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CB",
    "overall": 80,
    "pac": 75,
    "sho": 70,
    "pas": 76,
    "dri": 78,
    "def": 95,
    "phy": 78,
    "value": 1,
    "wage": 41,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 84,
    "photo": null
  },
  {
    "id": "cmrnsmsp50049kp2pbp4s3n95",
    "apiId": 550896,
    "firstName": "A.",
    "lastName": "E. Isek",
    "age": 18,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CB",
    "overall": 75,
    "pac": 75,
    "sho": 65,
    "pas": 70,
    "dri": 73,
    "def": 90,
    "phy": 73,
    "value": 3,
    "wage": 18,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 78,
    "photo": null
  },
  {
    "id": "cmrnsmsp8004bkp2pvk3a4vy1",
    "apiId": 2973,
    "firstName": "A.",
    "lastName": "Murillu",
    "age": 29,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CB",
    "overall": 72,
    "pac": 73,
    "sho": 62,
    "pas": 67,
    "dri": 76,
    "def": 87,
    "phy": 75,
    "value": 1,
    "wage": 47,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 75,
    "photo": null
  },
  {
    "id": "cmrnsmspa004dkp2pwkcdt1ov",
    "apiId": 333137,
    "firstName": "K.",
    "lastName": "Ouattaro",
    "age": 21,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CB",
    "overall": 82,
    "pac": 83,
    "sho": 72,
    "pas": 85,
    "dri": 84,
    "def": 97,
    "phy": 82,
    "value": 6,
    "wage": 15,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 84,
    "photo": null
  },
  {
    "id": "cmrnsmspc004fkp2p5eulm8o4",
    "apiId": 50046,
    "firstName": "E.",
    "lastName": "Topça",
    "age": 25,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CB",
    "overall": 73,
    "pac": 76,
    "sho": 63,
    "pas": 72,
    "dri": 75,
    "def": 88,
    "phy": 73,
    "value": 9,
    "wage": 22,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 77,
    "photo": null
  },
  {
    "id": "cmrnsmspe004hkp2p6jhqf4iz",
    "apiId": 25406,
    "firstName": "F.",
    "lastName": "Uduokhae",
    "age": 28,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CB",
    "overall": 83,
    "pac": 84,
    "sho": 73,
    "pas": 78,
    "dri": 84,
    "def": 98,
    "phy": 82,
    "value": 8,
    "wage": 43,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 87,
    "photo": null
  },
  {
    "id": "cmrnsmspg004jkp2psqtamw3g",
    "apiId": 1987,
    "firstName": "R.",
    "lastName": "Yılmoz",
    "age": 24,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CB",
    "overall": 71,
    "pac": 75,
    "sho": 61,
    "pas": 68,
    "dri": 70,
    "def": 86,
    "phy": 72,
    "value": 7,
    "wage": 12,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 73,
    "photo": null
  },
  {
    "id": "cmrnsmspj004lkp2pgr68084v",
    "apiId": 361397,
    "firstName": "F.",
    "lastName": "Kerem Oy",
    "age": 21,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CM",
    "overall": 84,
    "pac": 83,
    "sho": 74,
    "pas": 84,
    "dri": 80,
    "def": 69,
    "phy": 82,
    "value": 2,
    "wage": 27,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 88,
    "photo": null
  },
  {
    "id": "cmrnsmspl004nkp2pmc8q1i1c",
    "apiId": 549,
    "firstName": "V.",
    "lastName": "Čarný",
    "age": 28,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CM",
    "overall": 80,
    "pac": 81,
    "sho": 70,
    "pas": 81,
    "dri": 79,
    "def": 65,
    "phy": 83,
    "value": 10,
    "wage": 22,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 84,
    "photo": null
  },
  {
    "id": "cmrnsmspn004pkp2py4k2ibks",
    "apiId": 446824,
    "firstName": "I.",
    "lastName": "Fakile",
    "age": 19,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CM",
    "overall": 71,
    "pac": 69,
    "sho": 61,
    "pas": 74,
    "dri": 66,
    "def": 56,
    "phy": 72,
    "value": 13,
    "wage": 37,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 74,
    "photo": null
  },
  {
    "id": "cmrnsmspp004rkp2pbkmz99iw",
    "apiId": 1998,
    "firstName": "K.",
    "lastName": "Yılmoz",
    "age": 25,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CM",
    "overall": 78,
    "pac": 76,
    "sho": 68,
    "pas": 75,
    "dri": 78,
    "def": 63,
    "phy": 82,
    "value": 15,
    "wage": 46,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 79,
    "photo": null
  },
  {
    "id": "cmrnsmspr004tkp2pm814dml6",
    "apiId": 37155,
    "firstName": "O.",
    "lastName": "Kökçä",
    "age": 25,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CM",
    "overall": 79,
    "pac": 82,
    "sho": 69,
    "pas": 82,
    "dri": 78,
    "def": 64,
    "phy": 77,
    "value": 14,
    "wage": 48,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 81,
    "photo": null
  },
  {
    "id": "cmrnsmspt004vkp2pudmiz9sw",
    "apiId": 18786,
    "firstName": "W.",
    "lastName": "Ndide",
    "age": 29,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CM",
    "overall": 72,
    "pac": 75,
    "sho": 62,
    "pas": 67,
    "dri": 70,
    "def": 57,
    "phy": 68,
    "value": 3,
    "wage": 57,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 74,
    "photo": null
  },
  {
    "id": "cmrnsmspw004xkp2preluam5i",
    "apiId": 316904,
    "firstName": "J.",
    "lastName": "Olaiton",
    "age": 23,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CM",
    "overall": 76,
    "pac": 72,
    "sho": 66,
    "pas": 74,
    "dri": 76,
    "def": 61,
    "phy": 78,
    "value": 15,
    "wage": 41,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 78,
    "photo": null
  },
  {
    "id": "cmrnsmspy004zkp2pxe5otmkf",
    "apiId": 24807,
    "firstName": "S.",
    "lastName": "Özcon",
    "age": 27,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CM",
    "overall": 75,
    "pac": 78,
    "sho": 65,
    "pas": 78,
    "dri": 75,
    "def": 60,
    "phy": 74,
    "value": 3,
    "wage": 45,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 75,
    "photo": null
  },
  {
    "id": "cmrnsmsq00051kp2p6iww67bi",
    "apiId": 25324,
    "firstName": "M.",
    "lastName": "Rashico",
    "age": 29,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CM",
    "overall": 70,
    "pac": 66,
    "sho": 60,
    "pas": 65,
    "dri": 65,
    "def": 55,
    "phy": 68,
    "value": 10,
    "wage": 54,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 73,
    "photo": null
  },
  {
    "id": "cmrnsmsq20053kp2pbr33ce7o",
    "apiId": 529859,
    "firstName": "D.",
    "lastName": "Sahen",
    "age": 18,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "CM",
    "overall": 76,
    "pac": 74,
    "sho": 66,
    "pas": 79,
    "dri": 74,
    "def": 61,
    "phy": 78,
    "value": 2,
    "wage": 47,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 80,
    "photo": null
  },
  {
    "id": "cmrnsmsq40055kp2peot483l4",
    "apiId": 630520,
    "firstName": "S.",
    "lastName": "Bircan Ahmat",
    "age": 18,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "ST",
    "overall": 79,
    "pac": 76,
    "sho": 89,
    "pas": 80,
    "dri": 76,
    "def": 64,
    "phy": 83,
    "value": 7,
    "wage": 19,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 82,
    "photo": null
  },
  {
    "id": "cmrnsmsq60057kp2pnh1f69ny",
    "apiId": 436179,
    "firstName": "M.",
    "lastName": "Hekimoğla",
    "age": 18,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "ST",
    "overall": 80,
    "pac": 75,
    "sho": 90,
    "pas": 84,
    "dri": 80,
    "def": 65,
    "phy": 80,
    "value": 1,
    "wage": 33,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 81,
    "photo": null
  },
  {
    "id": "cmrnsmsq80059kp2p7efxv29d",
    "apiId": 336567,
    "firstName": "S.",
    "lastName": "Kılıçsuy",
    "age": 20,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "ST",
    "overall": 70,
    "pac": 74,
    "sho": 80,
    "pas": 68,
    "dri": 66,
    "def": 55,
    "phy": 66,
    "value": 8,
    "wage": 28,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 73,
    "photo": null
  },
  {
    "id": "cmrnsmsqb005bkp2pfmnw24b9",
    "apiId": 34710,
    "firstName": "O.",
    "lastName": "Hyeon-Gya",
    "age": 24,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "ST",
    "overall": 73,
    "pac": 77,
    "sho": 83,
    "pas": 69,
    "dri": 71,
    "def": 58,
    "phy": 68,
    "value": 11,
    "wage": 14,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 76,
    "photo": null
  },
  {
    "id": "cmrnsmsqd005dkp2p2uvogiei",
    "apiId": 633057,
    "firstName": "A.",
    "lastName": "Pagdo",
    "age": 17,
    "nationality": "Bilinmiyor",
    "clubId": "549",
    "position": "ST",
    "overall": 75,
    "pac": 79,
    "sho": 85,
    "pas": 72,
    "dri": 74,
    "def": 60,
    "phy": 76,
    "value": 3,
    "wage": 32,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 76,
    "photo": null
  },
  {
    "id": "cmrnsmuej005fkp2pns71ot4b",
    "apiId": 394215,
    "firstName": "O.",
    "lastName": "Çevikkon",
    "age": 19,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "GK",
    "overall": 80,
    "pac": 82,
    "sho": 70,
    "pas": 77,
    "dri": 80,
    "def": 65,
    "phy": 77,
    "value": 8,
    "wage": 54,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 83,
    "photo": null
  },
  {
    "id": "cmrnsmuel005hkp2p59u2ysbp",
    "apiId": 593479,
    "firstName": "E.",
    "lastName": "Colok",
    "age": 20,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "GK",
    "overall": 75,
    "pac": 77,
    "sho": 65,
    "pas": 72,
    "dri": 75,
    "def": 60,
    "phy": 78,
    "value": 11,
    "wage": 29,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 77,
    "photo": null
  },
  {
    "id": "cmrnsmueo005jkp2pleff88td",
    "apiId": 526,
    "firstName": "A.",
    "lastName": "Onano",
    "age": 29,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "GK",
    "overall": 70,
    "pac": 74,
    "sho": 60,
    "pas": 71,
    "dri": 67,
    "def": 55,
    "phy": 66,
    "value": 14,
    "wage": 15,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 72,
    "photo": null
  },
  {
    "id": "cmrnsmueq005lkp2pqfrnq8lt",
    "apiId": 479721,
    "firstName": "A.",
    "lastName": "Yıldıram",
    "age": 19,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "GK",
    "overall": 79,
    "pac": 80,
    "sho": 69,
    "pas": 75,
    "dri": 78,
    "def": 64,
    "phy": 80,
    "value": 14,
    "wage": 13,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 79,
    "photo": null
  },
  {
    "id": "cmrnsmues005nkp2p8n7crnk8",
    "apiId": 62490,
    "firstName": "S.",
    "lastName": "Akayden",
    "age": 31,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CB",
    "overall": 77,
    "pac": 77,
    "sho": 67,
    "pas": 79,
    "dri": 78,
    "def": 92,
    "phy": 81,
    "value": 14,
    "wage": 58,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 77,
    "photo": null
  },
  {
    "id": "cmrnsmueu005pkp2p55ey7ubp",
    "apiId": 63627,
    "firstName": "A.",
    "lastName": "Bataguv",
    "age": 23,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CB",
    "overall": 71,
    "pac": 68,
    "sho": 61,
    "pas": 70,
    "dri": 73,
    "def": 86,
    "phy": 66,
    "value": 11,
    "wage": 27,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 73,
    "photo": null
  },
  {
    "id": "cmrnsmuew005rkp2p3konhhig",
    "apiId": 338815,
    "firstName": "A.",
    "lastName": "Boşlak",
    "age": 22,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CB",
    "overall": 82,
    "pac": 86,
    "sho": 72,
    "pas": 85,
    "dri": 77,
    "def": 97,
    "phy": 82,
    "value": 9,
    "wage": 10,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 82,
    "photo": null
  },
  {
    "id": "cmrnsmuey005tkp2pvsw42bot",
    "apiId": 496868,
    "firstName": "T.",
    "lastName": "İnca",
    "age": 18,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CB",
    "overall": 70,
    "pac": 74,
    "sho": 60,
    "pas": 74,
    "dri": 70,
    "def": 85,
    "phy": 70,
    "value": 15,
    "wage": 13,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 72,
    "photo": null
  },
  {
    "id": "cmrnsmuf1005vkp2p3o9y7mp6",
    "apiId": 308689,
    "firstName": "S.",
    "lastName": "Lopes Cabrol",
    "age": 23,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CB",
    "overall": 74,
    "pac": 74,
    "sho": 64,
    "pas": 75,
    "dri": 72,
    "def": 89,
    "phy": 71,
    "value": 3,
    "wage": 33,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 74,
    "photo": null
  },
  {
    "id": "cmrnsmuf2005xkp2pwfo7sbnt",
    "apiId": 323369,
    "firstName": "M.",
    "lastName": "Løvek",
    "age": 22,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CB",
    "overall": 70,
    "pac": 67,
    "sho": 60,
    "pas": 71,
    "dri": 66,
    "def": 85,
    "phy": 72,
    "value": 1,
    "wage": 35,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 72,
    "photo": null
  },
  {
    "id": "cmrnsmuf4005zkp2p1oes5jxg",
    "apiId": 332056,
    "firstName": "W.",
    "lastName": "Pino",
    "age": 23,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CB",
    "overall": 74,
    "pac": 75,
    "sho": 64,
    "pas": 71,
    "dri": 78,
    "def": 89,
    "phy": 77,
    "value": 1,
    "wage": 13,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 78,
    "photo": null
  },
  {
    "id": "cmrnsmuf60061kp2poqh4fu0z",
    "apiId": 39,
    "firstName": "S.",
    "lastName": "Saveć",
    "age": 35,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CB",
    "overall": 84,
    "pac": 85,
    "sho": 74,
    "pas": 79,
    "dri": 86,
    "def": 99,
    "phy": 80,
    "value": 10,
    "wage": 36,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 86,
    "photo": null
  },
  {
    "id": "cmrnsmuf80063kp2p0k835szi",
    "apiId": 610902,
    "firstName": "A.",
    "lastName": "Tekka",
    "age": 17,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CB",
    "overall": 72,
    "pac": 71,
    "sho": 62,
    "pas": 67,
    "dri": 76,
    "def": 87,
    "phy": 75,
    "value": 8,
    "wage": 19,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 73,
    "photo": null
  },
  {
    "id": "cmrnsmufa0065kp2pjlz17x2f",
    "apiId": 493968,
    "firstName": "B.",
    "lastName": "BaÅkon",
    "age": 19,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CM",
    "overall": 80,
    "pac": 84,
    "sho": 70,
    "pas": 78,
    "dri": 75,
    "def": 65,
    "phy": 79,
    "value": 14,
    "wage": 44,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 84,
    "photo": null
  },
  {
    "id": "cmrnsmufd0067kp2pju6b20ty",
    "apiId": 274355,
    "firstName": "B.",
    "lastName": "Bouchouare",
    "age": 24,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CM",
    "overall": 73,
    "pac": 72,
    "sho": 63,
    "pas": 74,
    "dri": 68,
    "def": 58,
    "phy": 77,
    "value": 13,
    "wage": 55,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 75,
    "photo": null
  },
  {
    "id": "cmrnsmuff0069kp2pcra90mxm",
    "apiId": 593482,
    "firstName": "Y.",
    "lastName": "Cubukca",
    "age": 17,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CM",
    "overall": 84,
    "pac": 80,
    "sho": 74,
    "pas": 82,
    "dri": 85,
    "def": 69,
    "phy": 80,
    "value": 2,
    "wage": 24,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 86,
    "photo": null
  },
  {
    "id": "cmrnsmufi006bkp2px8bq83un",
    "apiId": 598478,
    "firstName": "O.",
    "lastName": "Ertam",
    "age": 18,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CM",
    "overall": 71,
    "pac": 66,
    "sho": 61,
    "pas": 75,
    "dri": 70,
    "def": 56,
    "phy": 68,
    "value": 9,
    "wage": 37,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 73,
    "photo": null
  },
  {
    "id": "cmrnsmufk006dkp2pxic7rl8d",
    "apiId": 62323,
    "firstName": "M.",
    "lastName": "Eskihelloç",
    "age": 28,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CM",
    "overall": 76,
    "pac": 78,
    "sho": 66,
    "pas": 72,
    "dri": 75,
    "def": 61,
    "phy": 76,
    "value": 6,
    "wage": 23,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 78,
    "photo": null
  },
  {
    "id": "cmrnsmufm006fkp2p1nwa43g9",
    "apiId": 474591,
    "firstName": "C.",
    "lastName": "Inao OuloÃ¯",
    "age": 19,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CM",
    "overall": 70,
    "pac": 65,
    "sho": 60,
    "pas": 70,
    "dri": 71,
    "def": 55,
    "phy": 65,
    "value": 9,
    "wage": 34,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 72,
    "photo": null
  },
  {
    "id": "cmrnsmufp006hkp2pgo5m1c6x",
    "apiId": 22408,
    "firstName": "T.",
    "lastName": "Jabol-Folcarelle",
    "age": 26,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CM",
    "overall": 78,
    "pac": 78,
    "sho": 68,
    "pas": 76,
    "dri": 75,
    "def": 63,
    "phy": 82,
    "value": 7,
    "wage": 28,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 82,
    "photo": null
  },
  {
    "id": "cmrnsmufr006jkp2pjdg5ahd6",
    "apiId": 158431,
    "firstName": "M.",
    "lastName": "Kabasakol",
    "age": 29,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CM",
    "overall": 80,
    "pac": 75,
    "sho": 70,
    "pas": 77,
    "dri": 80,
    "def": 65,
    "phy": 79,
    "value": 4,
    "wage": 38,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 82,
    "photo": null
  },
  {
    "id": "cmrnsmuft006lkp2p5d9un42t",
    "apiId": 1938,
    "firstName": "R.",
    "lastName": "Malinovskye",
    "age": 32,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CM",
    "overall": 76,
    "pac": 74,
    "sho": 66,
    "pas": 77,
    "dri": 72,
    "def": 61,
    "phy": 79,
    "value": 9,
    "wage": 41,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 77,
    "photo": null
  },
  {
    "id": "cmrnsmufw006nkp2pwfwfkmmc",
    "apiId": 422404,
    "firstName": "S.",
    "lastName": "Malkoçoğla",
    "age": 20,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CM",
    "overall": 70,
    "pac": 72,
    "sho": 60,
    "pas": 66,
    "dri": 66,
    "def": 55,
    "phy": 73,
    "value": 10,
    "wage": 43,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 70,
    "photo": null
  },
  {
    "id": "cmrnsmufy006pkp2pug425rkw",
    "apiId": 371027,
    "firstName": "C.",
    "lastName": "Nwaiwa",
    "age": 22,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CM",
    "overall": 71,
    "pac": 68,
    "sho": 61,
    "pas": 74,
    "dri": 67,
    "def": 56,
    "phy": 75,
    "value": 9,
    "wage": 25,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 71,
    "photo": null
  },
  {
    "id": "cmrnsmug0006rkp2p8pqs1dgf",
    "apiId": 49942,
    "firstName": "O.",
    "lastName": "Tufon",
    "age": 30,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CM",
    "overall": 71,
    "pac": 69,
    "sho": 61,
    "pas": 68,
    "dri": 66,
    "def": 56,
    "phy": 67,
    "value": 1,
    "wage": 54,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 73,
    "photo": null
  },
  {
    "id": "cmrnsmug2006tkp2p5t4bdj7d",
    "apiId": 47443,
    "firstName": "O.",
    "lastName": "Yokuşla",
    "age": 31,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "CM",
    "overall": 76,
    "pac": 76,
    "sho": 66,
    "pas": 80,
    "dri": 75,
    "def": 61,
    "phy": 72,
    "value": 1,
    "wage": 31,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 80,
    "photo": null
  },
  {
    "id": "cmrnsmug4006vkp2pf5jmz0a6",
    "apiId": 319514,
    "firstName": "C.",
    "lastName": "Çanok",
    "age": 21,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "ST",
    "overall": 79,
    "pac": 83,
    "sho": 89,
    "pas": 80,
    "dri": 74,
    "def": 64,
    "phy": 76,
    "value": 7,
    "wage": 31,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 81,
    "photo": null
  },
  {
    "id": "cmrnsmug6006xkp2p3xoaz0ul",
    "apiId": 43092,
    "firstName": "D.",
    "lastName": "Drăgaş",
    "age": 26,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "ST",
    "overall": 80,
    "pac": 75,
    "sho": 90,
    "pas": 76,
    "dri": 75,
    "def": 65,
    "phy": 77,
    "value": 1,
    "wage": 26,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 81,
    "photo": null
  },
  {
    "id": "cmrnsmug9006zkp2p03dcc0l6",
    "apiId": 610759,
    "firstName": "T.",
    "lastName": "Karadenez",
    "age": 17,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "ST",
    "overall": 77,
    "pac": 75,
    "sho": 87,
    "pas": 76,
    "dri": 77,
    "def": 62,
    "phy": 74,
    "value": 3,
    "wage": 59,
    "contractEnd": 2025,
    "height": 180,
    "weight": 75,
    "potential": 80,
    "photo": null
  },
  {
    "id": "cmrnsmugb0071kp2p4u23ttlt",
    "apiId": 107660,
    "firstName": "M.",
    "lastName": "Mimaroğla",
    "age": 31,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "ST",
    "overall": 81,
    "pac": 84,
    "sho": 91,
    "pas": 83,
    "dri": 81,
    "def": 66,
    "phy": 79,
    "value": 4,
    "wage": 39,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 85,
    "photo": null
  },
  {
    "id": "cmrnsmuge0073kp2pwgb5s0jo",
    "apiId": 3638,
    "firstName": "E.",
    "lastName": "Muçe",
    "age": 24,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "ST",
    "overall": 80,
    "pac": 78,
    "sho": 90,
    "pas": 76,
    "dri": 75,
    "def": 65,
    "phy": 82,
    "value": 12,
    "wage": 17,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 81,
    "photo": null
  },
  {
    "id": "cmrnsmugg0075kp2piqrwfg5o",
    "apiId": 50246,
    "firstName": "U.",
    "lastName": "Nayer",
    "age": 32,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "ST",
    "overall": 72,
    "pac": 74,
    "sho": 82,
    "pas": 72,
    "dri": 75,
    "def": 57,
    "phy": 68,
    "value": 7,
    "wage": 28,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 76,
    "photo": null
  },
  {
    "id": "cmrnsmugi0077kp2pibyah7kq",
    "apiId": 15812,
    "firstName": "P.",
    "lastName": "Onuacha",
    "age": 31,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "ST",
    "overall": 73,
    "pac": 77,
    "sho": 83,
    "pas": 77,
    "dri": 71,
    "def": 58,
    "phy": 73,
    "value": 4,
    "wage": 41,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 77,
    "photo": null
  },
  {
    "id": "cmrnsmugk0079kp2pl3grfe0b",
    "apiId": 454973,
    "firstName": "N.",
    "lastName": "Saviolu",
    "age": 21,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "ST",
    "overall": 75,
    "pac": 75,
    "sho": 85,
    "pas": 78,
    "dri": 73,
    "def": 60,
    "phy": 72,
    "value": 10,
    "wage": 14,
    "contractEnd": 2026,
    "height": 180,
    "weight": 75,
    "potential": 79,
    "photo": null
  },
  {
    "id": "cmrnsmugn007bkp2pogxvbd6m",
    "apiId": 161790,
    "firstName": "A.",
    "lastName": "Şimşer",
    "age": 23,
    "nationality": "Bilinmiyor",
    "clubId": "998",
    "position": "ST",
    "overall": 84,
    "pac": 82,
    "sho": 94,
    "pas": 85,
    "dri": 88,
    "def": 69,
    "phy": 88,
    "value": 15,
    "wage": 58,
    "contractEnd": 2027,
    "height": 180,
    "weight": 75,
    "potential": 85,
    "photo": null
  }
];

const positionMap = {
  'GK': [],
  'CB': ['CDM', 'RB', 'LB'],
  'LB': ['LWB', 'LM', 'CB'],
  'RB': ['RWB', 'RM', 'CB'],
  'LWB': ['LB', 'LM', 'LW'],
  'RWB': ['RB', 'RM', 'RW'],
  'CDM': ['CM', 'CB'],
  'CM': ['CDM', 'CAM', 'LM', 'RM'],
  'CAM': ['CM', 'CF', 'LW', 'RW'],
  'LM': ['LW', 'LWB', 'CM'],
  'RM': ['RW', 'RWB', 'CM'],
  'LW': ['LM', 'ST', 'CF'],
  'RW': ['RM', 'ST', 'CF'],
  'CF': ['ST', 'CAM', 'LW', 'RW'],
  'ST': ['CF', 'LW', 'RW']
};

players.forEach(p => {
  if (!p.alternatePositions) {
    const alternates = positionMap[p.position] || [];
    // Rastgele 1 veya 2 adet 2. ve 3. mevki seç (oyuncu kalitesine göre)
    // Kaliteli oyuncuların daha fazla çok yönlü olma ihtimali var
    const numAlts = p.overall > 75 ? (Math.random() > 0.5 ? 2 : 1) : 1;
    
    // Diziyi karıştırıp ilk numAlts kadarını al
    p.alternatePositions = alternates
      .sort(() => 0.5 - Math.random())
      .slice(0, numAlts);
  }
});

const ChampionMasterData = {
  leagues,
  clubs,
  players
};
export default ChampionMasterData;
